spring.application.name=taskmanager

# Data Base
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=taskuser
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/app.log

# JWT
jwt.secret=chave-secreta-muito-longa-para-desenvolvimento-123456789
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000